### ISSUE TITLE
Error in RPANDA::mantel_test(as.dist(eco_B) ~ as.dist(cophe_B), nperm = nperm, : Matrix not square.

### ISSUE THREAD

**Issue by Cxiaona** [BPerezLamarque/Phylosignal_network#1]
1.Same data why the first step reports an error and the second part works fine.
2.But another data that is not 'square' works fine.
3.I have ruled out the problem of mismatch between the node names in the genealogy tree and the species names in the matrix (network).
![1](https://github.com/user-attachments/assets/dba70510-80ea-4292-9246-665d12b5f9b5)
![222](https://github.com/user-attachments/assets/bcde9edd-ea33-4b38-8c83-250976824f3d)

**Comment by BPerezLamarque** [comment]
Dear Cxiaona,
Indeed, the problem may come from mismatches and/or duplicates between the names in the phylogenetic trees and the network. If you send me directly the data I can try to look at the origin of the problem and try to debug it, as it is impossible to find the origin of your problem without the data. 
All best, 
Benoît

**Comment by BPerezLamarque** [comment]
Dear Cxiaona, 

I have looked at the data you sent me and the problem comes from your phylogenetic tree of clade B : tree_B contains branch lengths that are NA! So R can not compute phylogenetic distances between these branches. 

I have replaced branches lengths of NA by 0 and the script works fine now (see the following code). 

All best, 
Benoît

PS : it worked for measuring the signal in tree_A and not in tree_B. When using permutation = "shuffle", it tried to compute the phylogenetic signal in tree_A and tree_B and crashed. When using permutation = "nbpartners", it only computed the signal in tree_A and it worked fine. 

######

rm(list=ls())

library(RPANDA)
library(ape)

NAtree_A <- read.tree(file = '20241217_NA_plant_tree.nwk')
length(NAtree_A$tip.label)

NAtree_B <- read.tree(file = '20241217_NA_miner-tree_1.phy')
length(NAtree_B$tip.label)

NAtree_B$edge.length # The problem comes from a NA in the branch lengths of tree B 
NAtree_B$edge.length[is.na(NAtree_B$edge.length)] <- 0


NAnetwork <- read.table('NA_matrix.csv', header = T, sep=",")
rownames(NAnetwork) <- NAnetwork$X
NAnetwork <- NAnetwork[,NAtree_A$tip.label]
dim(NAnetwork)


phylosignal_network(NAnetwork, NAtree_A, NAtree_B,
                    method = "Jaccard_weighted", correlation = "Pearson",
                    permutation = "shuffle")
